org: dbkompare
app: db-kompare
service: comment
configValidationMode: error

useDotenv: true

custom:
  lambdaInitialArn: arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:${self:service}-${self:provider.stage}
  commentsTableArn: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.COMMENTS_TABLE}
  usersTableArn: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.USERS_TABLE}
  quizProgressTableArn: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.QUIZ_PROGRESS_TABLE}
  UserAchievementsTableArn: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.environment.USER_ACHIEVEMENTS_TABLE}

  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  profile: dbkompare
  versionFunctions: false
  environment:
    COMMENTS_TABLE: db-kompare-comments-${self:provider.stage}
    USERS_TABLE: db-kompare-users-${self:provider.stage}
    QUIZ_PROGRESS_TABLE: db-kompare-user-quiz-progress-${self:provider.stage}
    USER_ACHIEVEMENTS_TABLE: db-kompare-user-achievements-${self:provider.stage}


  apiGateway:
    apiKeys:
      - name: comment-key

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource:
            - ${self:custom.commentsTableArn} # Permission for comments table
            - ${self:custom.usersTableArn} # Permission for users table
            - ${self:custom.commentsTableArn}/index/* # Permission for comments table indexes
            - ${self:custom.quizProgressTableArn} # Permission for quiz progress table
            - ${self:custom.quizProgressTableArn}/index/* # Permission for quiz progress table indexes
            - ${self:custom.UserAchievementsTableArn} # Permission for user achievements table
            - ${self:custom.UserAchievementsTableArn}/index/* # Permission for user achievements table indexes

functions:
  createComment:
    handler: functions/comments/createComment.handler
    events:
      - http:
          path: /create-comment
          method: post
          private: true
          cors: true
  updateComment:
    handler: functions/comments/updateComment.handler
    events:
      - http:
          path: /update-comment
          method: patch
          private: true
          cors: true
  getCommentsByDatabaseIds:
    handler: functions/comments/getCommentsByDatabaseIds.handler
    events:
      - http:
          path: /get-comments
          method: post
          private: true
          cors: true
  deleteComment:
    handler: functions/comments/deleteComment.handler
    events:
      - http:
          path: /delete-comment
          method: delete
          private: true
          cors: true
  updateCommentStatus:
    handler: functions/comments/updateCommentStatus.handler
    events:
      - http:
          path: /update-comment-status
          method: patch
          private: true
          cors: true
  dbRating:
    handler: functions/db-rating/dbRating.handler
    events:
      - http:
          path: /db-rating
          method: post
          private: true
          cors: true

  createQuizProgress:
    handler: functions/quizzes/createQuizProgress.handler
    events:
      - http:
          path: /create-quiz-progress
          method: post
          private: true
          cors: true

  getQuizProgress:
    handler: functions/quizzes/getQuizProgress.handler
    events:
      - http:
          path: /get-quiz-progress
          method: get
          private: true
          cors: true
          
  updateQuizProgress:
    handler: functions/quizzes/updateQuizProgress.handler
    events:
      - http:
          path: /update-quiz-progress
          method: put
          private: true
          cors: true

# ---------------USER ACHIEVEMENTS FUNCTIONS-------------
  processAchievement:
    handler: functions/user-achievements/processAchievement.handler
    events:
      - http:
          path: /process-achievement
          method: post
          private: true
          cors: true
          
  # This function is used to process reminders for user streaks
  # processReminderForStreak:
  #   handler: functions/user-achievements/processReminderForStreak.handler
  #   events:
  #     - schedule:
  #         rate: rate(1 hour) # Runs every hour

  # --------------- STRIPE FUNCTIONS -------------

  createPayemtIntent:
    handler: functions/user-payments/createPaymentIntent.handler
    events:
      - http:
          path: /create-payment-intent
          method: post
          private: true
          cors: true
    layers:
      - arn:aws:lambda:${self:provider.region}:${aws:accountId}:layer:stripe-layer:2